### ISSUE TITLE
Error message while clicking on Custom Report link

### ISSUE THREAD

**Issue by lajish** [zeyuLiang/redmine_customized_report#2]
Hi there,

I installed this plugin successfully but on clicking Custom report link on issues page, I ended with an error. Please help me if i am wrong anywhere. I am using redmine 2.5.1

![image](https://cloud.githubusercontent.com/assets/6768694/3140855/624f3726-e945-11e3-97de-49e5b7c4d7d4.png)

Moreover I have another request, please rename 'custom_report' link as 'Custom Report'

**Comment by ccummings135** [comment]
I am having the same issue. with the page not found
Also on the right hand side. My Calendar wants to be on the same line as custom_report. 
I would be grateful for any help. 

lajish, 
On the "rename 'custom_report' link as 'Custom Report'"
Go to the en.yml file change(line 4) custom_report: "custom_report" to custom_report: "Custom Report"

**Comment by lajish** [comment]
Hi ccummings135,

Thanks for your help. I am a newbie to this redmine and still learning about features. Anyway once again thanks.

But the main issue is still existing. Hope author will fix it very soon.

**Comment by ccummings135** [comment]
Yes the main issue still exists and like you I hope he will provide a fix or guidance on how to fix this issue. 
I like you am new at a lot of this but read forums when I find issues with plugins trying to fix them.

**Comment by zeyuLiang** [comment]
Sorry,I can't recreate the problem under pure 2.5.0 and 2.5.1 redmine.. Unless you give me the log details,I don't know what to do.

**Comment by ccummings135** [comment]
Not Found

The requested URL /projects/tesu/issues/customized_reports was not found on this server.
Nothing gets to the log. One thing I did notice is the extention 
            /projects/tesu/issues/customized_reports?set_filter=1
My project extension is /redmine/projects/tesu/issues/customized_reports?set_filter=1
I have changed that in the routes.rb file I get Page Cannot be found and the following in the log:

Completed 200 OK in 5391ms (Views: 1968.8ms | ActiveRecord: 671.9ms)
Started GET "/redmine/projects/tesu/issues/customized_reports?set_filter=1" for 127.0.0.1 at 2014-06-04 06:22:45 -0500

ActionController::RoutingError (No route matches [GET] "/projects/tesu/issues/customized_reports"):
  actionpack (3.2.12) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.12) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  railties (3.2.12) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.12) lib/rails/rack/logger.rb:16:in`block in call'
  activesupport (3.2.12) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.12) lib/rails/rack/logger.rb:16:in`call'
  actionpack (3.2.12) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.12) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.12) lib/action_dispatch/middleware/static.rb:62:in`call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in`fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in`call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.12) lib/rails/engine.rb:479:in`call'
  railties (3.2.12) lib/rails/application.rb:223:in `call'
  railties (3.2.12) lib/rails/railtie/configurable.rb:30:in`method_missing'
  rack (1.4.5) lib/rack/urlmap.rb:64:in `block in call'
  rack (1.4.5) lib/rack/urlmap.rb:49:in`each'
  rack (1.4.5) lib/rack/urlmap.rb:49:in `call'
  thin (1.3.1) lib/thin/connection.rb:80:in`block in pre_process'
  thin (1.3.1) lib/thin/connection.rb:78:in `catch'
  thin (1.3.1) lib/thin/connection.rb:78:in`pre_process'
  thin (1.3.1) lib/thin/connection.rb:53:in `process'
  thin (1.3.1) lib/thin/connection.rb:38:in`receive_data'
  eventmachine-1.0.0-x86 (mingw32) lib/eventmachine.rb:187:in `run_machine'
  eventmachine-1.0.0-x86 (mingw32) lib/eventmachine.rb:187:in`run'
  thin (1.3.1) lib/thin/backends/base.rb:61:in `start'
  thin (1.3.1) lib/thin/server.rb:159:in`start'
  thin (1.3.1) lib/thin/controllers/controller.rb:86:in `start'
  thin (1.3.1) lib/thin/runner.rb:185:in`run_command'
  thin (1.3.1) lib/thin/runner.rb:151:in `run!'
  thin (1.3.1) bin/thin:6:in`<top (required)>'
  bin/thin:16:in `load'
  bin/thin:16:in`<main>'

**Comment by zeyuLiang** [comment]
is your redmine  running under a sub-domain? Normal redmine url don't have a /redmine prefix.
Did you do something describe in http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_in_a_sub-URI, If you did, solutions may get different depending on the way you used.

**Comment by lajish** [comment]
Hi ZeyuLiang,

I am actually running bitnami distribution of redmine. Moreover plugin
installation also went hassle free on my win 7 32 bit machine.

> On June 5, 2014 at 1:08 PM zeyuLiang notifications@github.com wrote:
> 
>  is your redmine running under a sub-domain? Normal redmine url don't have a
> /redmine prefix.
>  Did you do something describe in
> http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_in_a_sub-URI,
> If you did, solutions may get different depending on the way you used.
> 
>  —
>  Reply to this email directly or view it on GitHub
> https://github.com/zeyuLiang/redmine_customized_report/issues/2#issuecomment-45189524
> .

Regs,
Lajish Lakshmanan

**Comment by zeyuLiang** [comment]
It is clear that the routing problem is caused by apache Reverse Proxy settings which is used in bitnami redmine. 
you may try this
http://wiki.bitnami.com/Applications/BitNami_Redmine#How_to_change_the_default_URL_to_the_root.3f  ,instead of manually change the plugins route.rb~

**Comment by ccummings135** [comment]
I would hate to change my apache settings, fear of creating other issues,  instead of changing route.rb
Do you know of another solution?
currently have several personal plugins, plus
Close_done_ratio
redmine_percent_done_configuration
redmine_people
redmine_monitoring_conrolling
redmine_issue_checklist
sidebar_hide

**Comment by zeyuLiang** [comment]
would you show me the result of command 'rake routes'？

**Comment by iranga** [comment]
I am also observing the following issue (Firefox 26.) when clicking on the client report link. running the web server on the defat Webrick.

Exception;
Started GET "/projects/firstproject/issues/customized_reports?set_filter=1" for 127.0.0.1 at 2014-06-06 12:46:46 +0530
Processing by CustomizedReportsController#index as HTML
  Parameters: {"set_filter"=>"1", "id"=>"firstproject"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 2ms

NoMethodError (undefined method `build_from_params' for #<ReportQuery:0x0000000593dbe0>):
  activemodel (3.2.8) lib/active_model/attribute_methods.rb:407:in`method_missing'
  activerecord (3.2.8) lib/active_record/attribute_methods.rb:149:in `method_missing'
  plugins/redmine_customized_report/app/helpers/report_queries_helper.rb:27:in`retrieve_report_query'
  plugins/redmine_customized_report/app/controllers/customized_reports_controller.rb:11:in `index'
  actionpack (3.2.8) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
  actionpack (3.2.8) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.8) lib/action_controller/metal/rendering.rb:10:in`process_action'
  actionpack (3.2.8) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.8) lib/active_support/callbacks.rb:469:in`_run__4343002462398123622__process_action__2477506450864639341__callbacks'
  activesupport (3.2.8) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.8) lib/active_support/callbacks.rb:385:in`_run_process_action_callbacks'
  activesupport (3.2.8) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.8) lib/abstract_controller/callbacks.rb:17:in`process_action'
  actionpack (3.2.8) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
  activesupport (3.2.8) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.8) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.8) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.8) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
  actionpack (3.2.8) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.8) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  actionpack (3.2.8) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.8) lib/abstract_controller/rendering.rb:45:in`process'
  actionpack (3.2.8) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.8) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  actionpack (3.2.8) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:73:in`call'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:36:in`call'
  /usr/lib/ruby/vendor_ruby/journey/router.rb:68:in `block in call'
  /usr/lib/ruby/vendor_ruby/journey/router.rb:56:in`each'
  /usr/lib/ruby/vendor_ruby/journey/router.rb:56:in `call'
  actionpack (3.2.8) lib/action_dispatch/routing/route_set.rb:600:in`call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in`context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/cookies.rb:339:in`call'
  activerecord (3.2.8) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.8) lib/active_support/callbacks.rb:405:in`_run__3405553963072609660__call__2644767800117304037__callbacks'
  activesupport (3.2.8) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.8) lib/active_support/callbacks.rb:385:in`_run_call_callbacks'
  activesupport (3.2.8) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.8) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.8) lib/rails/rack/logger.rb:26:in`call_app'
  railties (3.2.8) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.8) lib/action_dispatch/middleware/request_id.rb:22:in`call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in`call'
  activesupport (3.2.8) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in`call'
  actionpack (3.2.8) lib/action_dispatch/middleware/static.rb:62:in `call'
  /usr/lib/ruby/vendor_ruby/rack/cache/context.rb:136:in`forward'
  /usr/lib/ruby/vendor_ruby/rack/cache/context.rb:245:in `fetch'
  /usr/lib/ruby/vendor_ruby/rack/cache/context.rb:185:in`lookup'
  /usr/lib/ruby/vendor_ruby/rack/cache/context.rb:66:in `call!'
  /usr/lib/ruby/vendor_ruby/rack/cache/context.rb:51:in`call'
  railties (3.2.8) lib/rails/engine.rb:479:in `call'
  railties (3.2.8) lib/rails/application.rb:223:in`call'
  rack (1.4.5) lib/rack/content_length.rb:14:in `call'
  railties (3.2.8) lib/rails/rack/log_tailer.rb:17:in`call'
  rack (1.4.5) lib/rack/handler/webrick.rb:59:in `service'
  /usr/lib/ruby/1.9.1/webrick/httpserver.rb:138:in`service'
  /usr/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /usr/lib/ruby/1.9.1/webrick/server.rb:191:in`block in start_thread'

Environment:
  Redmine version                     2.1.2.stable
  Ruby version                           1.9.3 (x86_64-linux)
  Rails version                            3.2.8
  Environment                             production
  Database adapter                      Mysql2

**Comment by ccummings135** [comment]
Not sure what you are asking. Here is a copy of my rake redmine:plugins
C:\BitNami\redmine-2.2.3-0\apps\redmine\htdocs>rake redmine:plugins:migrate RAIL
S_ENV=production
Migrating close_done_ratio (Set Project % to 100% when closed)...
Migrating ecd_date (Redmine sets ECD date)...
Migrating qacp_number (Redmine set QACP Numbers)...
Migrating redmine_customized_report (Redmine Customized Report plugin)...
Migrating redmine_due_date_by_default (Auto QACP and Project Dates)...
Migrating redmine_issue_checklist (Redmine Issue Checklist plugin)...
Migrating redmine_monitoring_controlling (Redmine (Monitoring & Controlling | Mo
nitoramento & Controle))...
Migrating redmine_people (Redmine People plugin)...
Migrating redmine_percent_done_configuration (Percent Done Configuration plugin)
...
Migrating sidebar_hide (Sidebar Hide Plugin)...
Migrating tsco_start_date (Set Project Close date = to TSCO Start Date)...

**Comment by marikar** [comment]
Hi everyone,

Is there any update regarding this issue for Bitnami distribution? In my case there is no subdomain (No /redmine in the URL) but the link still does not work.

Thank you.

**Comment by ccummings135** [comment]
I did get try to get rid of my subdomain. That is when everything crashed! 
now that I restored everything and still have a sub domain this is what link I get
http://root/projects/tesu/issues/customized_reports?set_filter=1

But if I add the redmine 
http://root/redmine/projects/tesu/issues/customized_reports?set_filter=1
I see the page no problem. 

Error Message:
Not Found

The requested URL /projects/tesu/issues/customized_reports was not found on this server.

All other plugin links work fine.

**Comment by ccummings135** [comment]
After much hunting I got the custom reports to work with a sub uri
On a Bitnami system you will edit the environment.rb file (\Bitnami\redmine-2.6.1-2\apps\redmine\htdocs\config\environment.rb)
The VERY LAST line add the following: Rails.application.routes.default_url_options[:script_name] = '/redmine'
NOTE: my link to redmine is rooturl/redmine, so if you have rooturl/suburi change the /redmine to /suburi.
Your environment.rb will look like:

# Load the rails application

require File.expand_path('../application', **FILE**)

# Make sure there's no plugin in vendor/plugin before starting

vendor_plugins_dir = File.join(Rails.root, "vendor", "plugins")
if Dir.glob(File.join(vendor_plugins_dir, "*")).any?
  $stderr.puts "Plugins in vendor/plugins (#{vendor_plugins_dir}) are no longer allowed. " +
    "Please, put your Redmine plugins in the `plugins` directory at the root of your " +
    "Redmine directory (#{File.join(Rails.root, "plugins")})"
  exit 1
end

# Initialize the rails application

RedmineApp::Application.initialize!
Rails.application.routes.default_url_options[:script_name] = '/redmine'

Here is my configuration information also:
Environment:
  Redmine version                2.6.1.stable
  Ruby version                   2.0.0-p594 (2014-10-27) [i386-mingw32]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2

**Comment by lajish** [comment]
Hi ZeyuLiang,Thanks for your efforts. I have been looking for  this plugin to work. On Fri, Feb 20, 2015 at 9:20 PM, ccummings135 notifications@github.com wrote:After much hunting I got the custom reports to work with a sub uri
On a Bitnami system you will edit the environment.rb file (\Bitnami\redmine-2.6.1-2\apps\redmine\htdocs\config\environment.rb)
The VERY LAST line add the following: Rails.application.routes.default_url_options[:script_name] = '/redmine'
NOTE: my link to redmine is rooturl/redmine, so if you have rooturl/suburi change the /redmine to /suburi.
Your environment.rb will look like:

Load the rails application

require File.expand_path('../application', FILE)

Make sure there's no plugin in vendor/plugin before starting

vendor_plugins_dir = File.join(Rails.root, "vendor", "plugins")
if Dir.glob(File.join(vendor_plugins_dir, "*")).any?
  $stderr.puts "Plugins in vendor/plugins (#{vendor_plugins_dir}) are no longer allowed. " +
    "Please, put your Redmine plugins in the plugins directory at the root of your " +
    "Redmine directory (#{File.join(Rails.root, "plugins")})"
  exit 1
end

Initialize the rails application

RedmineApp::Application.initialize!
Rails.application.routes.default_url_options[:script_name] = '/redmine'

Here is my configuration information also:
Environment:
  Redmine version                2.6.1.stable
  Ruby version                   2.0.0-p594 (2014-10-27) [i386-mingw32]
  Rails version                  3.2.21
  Environment                    production
  Database adapter               Mysql2

**Comment by ccummings135** [comment]
Glad you got it working

**Comment by marikar** [comment]
I managed to solve the problem, while troubleshooting another plugin. The directory name of the plugin has to be "redmine_plugin_name" the same way it is defined in the init.rb file.

Then, performing the steps of plugin install (bundle install, rake etc) and restarting the redmine, the plugin is up and running!
